import json

# armor bookseller 
villager = ''' {Brain: {memories: {}}, 
                HurtByTimestamp: 0, 
                Attributes: 
                    [{Base: 48.0d, Modifiers: 
                    [{Amount: 0.06572175063694345d, Operation: 1, UUID: 
                    [I; -1306545626, 1395411539, -1563487579, 374214545], Name: "Random spawn bonus"}], 
                    Name: "minecraft:generic.follow_range"}, {Base: 0.5d, Name: "minecraft:generic.movement_speed"}], 
                FoodLevel: 0b, 
                Invulnerable: 0b, 
                FallFlying: 0b, 
                ForcedAge: 0, 
                Gossips: [], 
                PortalCooldown: 0, 
                AbsorptionAmount: 0.0f, 
                LastRestock: 0L, 
                FallDistance: 0.0f, 
                DeathTime: 0s, 
                Xp: 1, 
                LastGossipDecay: 487441L, 
                HandDropChances: [0.085f, 0.085f], 
                PersistenceRequired: 0b, 
                UUID: [I; -405135149, 1315390707, -1192280152, -877103080], 
                Tags: ["ve.checked"], 
                Age: 0, 
                Motion: [0.0d, -0.0784000015258789d, 0.0d], 
                Health: 20.0f, 
                LeftHanded: 0b, 
                Air: 300s, 
                OnGround: 1b, 
                Offers: 
                    {Recipes: 
                        [{maxUses: 2147483647, 
                            buyB: {id: "minecraft:emerald", Count: 16b}, 
                            buy: {id: "minecraft:diamond_helmet", Count: 1b, tag: {Damage: 0}}, 
                            sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 7, 
                            StoredEnchantments: 
                                [{lvl: 3s, id: "minecraft:respiration"}, 
                                {lvl: 1s, id: "minecraft:aqua_affinity"}, 
                                {lvl: 4s, id: "minecraft:protection"}, 
                                {lvl: 3s, id: "minecraft:unbreaking"}, 
                                {lvl: 1s, id: "minecraft:mending"}], 
                            display: {Name: '{"text":"Helm. Prot."}'}}}, 
                            xp: 1, 
                            uses: 0, 
                            priceMultiplier: 0.0f, 
                            specialPrice: 0, 
                            demand: 0, 
                            rewardExp: 1b}, 
                        
                        {maxUses: 2147483647, 
                            buyB: {id: "minecraft:emerald", Count: 16b}, 
                            buy: {id: "minecraft:diamond_helmet", Count: 1b, tag: {Damage: 0}}, 
                            sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 7, 
                            StoredEnchantments: 
                                [{lvl: 3s, id: "minecraft:respiration"},
                                {lvl: 1s, id: "minecraft:aqua_affinity"},
                                {lvl: 4s, id: "minecraft:blast_protection"},
                                {lvl: 3s, id: "minecraft:unbreaking"},
                                {lvl: 1s, id: "minecraft:mending"}],
                            display: {Name: '{"text":"Helm. Blst."}'}}},
                            xp: 1,
                            uses: 0,
                            priceMultiplier: 0.0f,
                            specialPrice: 0, demand: 0, rewardExp: 1b},
                        
                        {maxUses: 2147483647, 
                            buyB: {id: "minecraft:emerald", Count: 16b}, 
                            buy: {id: "minecraft:diamond_helmet", Count: 1b, tag: {Damage: 0}}, 
                            sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 7, 
                            StoredEnchantments: 
                                [{lvl: 3s, id: "minecraft:respiration"}, 
                                {lvl: 1s, id: "minecraft:aqua_affinity"}, 
                                {lvl: 4s, id: "minecraft:projectile_protection"}, 
                                {lvl: 3s, id: "minecraft:unbreaking"}, 
                                {lvl: 1s, id: "minecraft:mending"}], 
                            display: {Name: '{"text":"Helm. Proj."}'}}}, 
                            xp: 1, 
                            uses: 0, 
                            priceMultiplier: 0.0f, 
                            specialPrice: 0, 
                            demand: 0, 
                            rewardExp: 1b}, 
                        
                        {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_helmet", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 7, StoredEnchantments: [{lvl: 3s, id: "minecraft:respiration"}, {lvl: 1s, id: "minecraft:aqua_affinity"}, {lvl: 4s, id: "minecraft:fire_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Helm. Fire."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_chestplate", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 4s, id: "minecraft:protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Chst. Prot."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_chestplate", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 4s, id: "minecraft:blast_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Chst. Blst."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_chestplate", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 4s, id: "minecraft:projectile_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Chst. Proj,"}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_chestplate", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 4s, id: "minecraft:fire_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Chst. Fire."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_leggings", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 3s, id: "minecraft:swift_sneak"}, {lvl: 4s, id: "minecraft:protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Legs. Prot."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_leggings", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 3s, id: "minecraft:swift_sneak"}, {lvl: 4s, id: "minecraft:blast_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Legs. Blst."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_leggings", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 3s, id: "minecraft:swift_sneak"}, {lvl: 4s, id: "minecraft:projectile_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Legs. Proj."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_leggings", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 3, StoredEnchantments: [{lvl: 3s, id: "minecraft:swift_sneak"}, {lvl: 4s, id: "minecraft:fire_protection"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Legs. Fire."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:protection"}, {lvl: 3s, id: "minecraft:depth_strider"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Prot. Dpth."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:blast_protection"}, {lvl: 3s, id: "minecraft:depth_strider"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Blst. Dpth."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:projectile_protection"}, {lvl: 3s, id: "minecraft:depth_strider"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Proj. Dpth."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:fire_protection"}, {lvl: 3s, id: "minecraft:depth_strider"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Fire. Dpth."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:protection"}, {lvl: 2s, id: "minecraft:frost_walker"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Prot. Frst."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:blast_protection"}, {lvl: 2s, id: "minecraft:frost_walker"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Blst. Frst."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:projectile_protection"}, {lvl: 2s, id: "minecraft:frost_walker"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Proj. Frst."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}, {maxUses: 2147483647, buyB: {id: "minecraft:emerald", Count: 16b}, buy: {id: "minecraft:diamond_boots", Count: 1b, tag: {Damage: 0}}, sell: {id: "minecraft:enchanted_book", Count: 1b, tag: {RepairCost: 15, StoredEnchantments: [{lvl: 4s, id: "minecraft:fire_protection"}, {lvl: 2s, id: "minecraft:frost_walker"}, {lvl: 3s, id: "minecraft:soul_speed"}, {lvl: 4s, id: "minecraft:feather_falling"}, {lvl: 3s, id: "minecraft:unbreaking"}, {lvl: 1s, id: "minecraft:mending"}], display: {Name: '{"text":"Boot. Fire. Frst."}'}}}, xp: 1, uses: 0, priceMultiplier: 0.0f, specialPrice: 0, demand: 0, rewardExp: 1b}]}, Rotation: [-113.91121f, 0.0f], HandItems: [{}, {}], RestocksToday: 0, ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], CustomName: '"Armor Bookseller"', Pos: [152.5d, 71.0d, 2856.5d], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 1b, VillagerData: {profession: "minecraft:armorer", level: 5, type: "minecraft:plains"}, HurtTime: 0s, Inventory: []}'''
